### ISSUE TITLE
How to disable scan-for-updates in forks?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#159]
The scan-for-updates cron job runs also in forks of this repository, e.g. [in mine](https://github.com/fingolfin/PackageDistro). That can be a bit annoying, because it also ends up opening PRs there etc.

Perhaps we can limit it / make it abort itself if it is run on another repository, at least when triggered via a schedule (it should still be allowed to trigger it manually, for debugging/testing)

**Comment by FriedrichRober** [comment]
In my fork I have the opposite problem. GitHub doesn't find any workflows. Workflows are enabled on the fork.
