### ISSUE TITLE
bug: PR CI is not initially run for PRs generated by scan-for-updates workflow; only have closing & reopening the PR

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#16]
Perhaps there is an additional trigger flag we need to check or what?!?

**Comment by fingolfin** [comment]
Really weird. Example (for now): https://github.com/fingolfin/PackageDistro/pull/9

**Comment by fingolfin** [comment]
Oh, this is https://github.com/peter-evans/create-pull-request/issues/48

**Comment by fingolfin** [comment]
There are ton of workarounds listed there, and also in the README at https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

To me the one [using a GitHub App](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens) sounds most attractive, but also is work. I'll punt on this for now. So for now we'll just have to manually close and reopen new PRs to trigger a workflow, but this is sufficient to get things going.

**Comment by fingolfin** [comment]
Perhaps one can also use `workflow_run`, see e.g. <https://ospfranco.com/post/2021/05/10/how-to-trigger-a-github-actions-workflow-from-another-workflow/>?

Some more discussion: https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250/44


Perhaps @wilfwilson knows more?

**Comment by wilfwilson** [comment]
This is not something on which I have any particular expertise or insight. Well done for quickly identifying the cause!

I feel like it is _probably_ possible to get a reasonable solution involving one workflow triggering another one, but I'm not sure how that would work exactly.
