### ISSUE TITLE
bug: when there are no modified packages, job matrix is empty, resulting in an error

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#17]
This affects both the scan-for-updates and the PR workflow: when the matrix we generate is empty (e.g. because there are no update; or no removed packages; or no modified packages) then we get an error, like [in this run](https://github.com/fingolfin/PackageDistro/actions/runs/1898069448):

> [Test pull requests: .github#L1](https://github.com/fingolfin/PackageDistro/pull/8/files#annotation_2842265670)
> Error when evaluating 'strategy' for job 'remove-package'. .github/workflows/pull-request.yml (Line: 57, Col: 15): Matrix vector 'package' does not contain any values

What's the appropriate way to deal with this? Perhaps @wilfwilson knows?

**Comment by fingolfin** [comment]
My guess is one can solve this by inserting a suitable `if: {{ ... some expression... }}` into the jobs which use the generated build matrix, but I don't have time to figure it out right now

**Comment by wilfwilson** [comment]
I'll give it a go, adding something like `if: {{ $the matrix has the form of an empty matrix }}`. It may be a little fragile, but we'll see. Perhaps it's easiest to set an additional variable like "is nonempty matrix" and just use that directly.
