### ISSUE TITLE
Add a cron job (or multiple) which runs `test-all.yml` daily against the GAP master branch

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#217]
... so that we have a chance to notice regressions in packages introduced by GAP master

This needs the work by @FriedrichRober for detecting any status changes; but then we should also implement some kind of notification system, so that e.g. a Slack message with the failure is created, or perhaps even an issue could be opened (but I'd be careful, as there are sometimes intermittent failures and getting spammed with issues about those might become a problem...)

**Comment by FriedrichRober** [comment]
The question is, how can we avoid spam with packages like `hapcryst` or `xmodalg` that seem to change state between failure and success with each test-run.

**Comment by fingolfin** [comment]
The fluctuations are indeed a problem. @ChrisJefferson and me have been tracking this for some days now. The latest (very plausible!) theory is that the combination of `-march=native` as a compiler flag used by digraphs and semigroups (both of which are dependencies of all packages I'v seen "fluctuating") with `ccache` could be the cause. I'll investigate. Hopefully that'll cure it.

**Comment by fingolfin** [comment]
Resolved by PR #271.

Unfortunately the fluctuations due to crashes in semigroups/digraphs are not yet gone. But maybe my patches to turn off march=native simply did not work right. I gotta double check that.
