### ISSUE TITLE
Automatically deal with multiple packages being updated and needing to be tested and merged simultaneously

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#249]
Recently `cap` and `linearalgebraforcap` were updated at the same time. The PRs for both recorded failures -- because each needed the other to pass.

This is not uncomment esp. for packages from homalg-project and cap-project (CC @mohamed-barakat @zickgraf).

It would be good if in these cases, a single PR was opened instead of two. But how to achieve this? One way to deal with it would be if we had a full concept of "meta packages" in GAP. Then that would give a natural way to show the grouping. On an implementation level, if we detect in one scan-for-updates round that a meta package is updated, we generate a single PR for it and all its subpackages, but none for its subpackages on their own.

Unfortunately the [GAP PR for meta packages](https://github.com/gap-system/gap/pull/2267) is stalled and AFAIK nobody is working in it right now.

So as a stop-gap substitute, we could manually create a list of "meta packages": i.e. a file somewhere that contains a list of lists of package names, each list constituting the "subpackages" of an (implicit) meta package. Of course this would be adhoc, but I think it would share most of the code with the "clean" solution, but could be implemented right now.

The one drawback I see is that this list would be here, so if e.g. the homalg team wants to add a package to their "meta package", the package distro won't know about it until someone edits our list here. But on the upside, that's not hard, and the homalg team could even do it themselves (by submitting a suitable PR).

**Comment by fingolfin** [comment]
Some more details on how I envision the implementation: 
- decide for a place to put this "list of lists of related packages" (could be in a JSON file; as part of a JSON script; whatever makes implementation easiest
- edit the "Creates jobs for modified packages" step in `.github/workflows/scan-for-updates.yml` to heed that list. One option would be to turn that shell script into a Python script (stored in `tools/`), which would make it trivial to add the checks I described. But of course one can also implement it all as bash code or whatnot
- profit

**Comment by mohamed-barakat** [comment]
> The one drawback I see is that this list would be here, so if e.g. the homalg team wants to add a package to their "meta package", the package distro won't know about it until someone edits our list here. But on the upside, that's not hard, and the homalg team could even do it themselves (by submitting a suitable PR).

We will keep this in mind in case we plan to submit a new (sub)package. In that case, we have to inform the GAP team anyway. As you mentioned, this could be a path toward a meta-package support.

**Comment by zickgraf** [comment]
I agree with @mohamed-barakat that keeping a manual list would be fine for us, as it would rarely change. But just to throw in an idea: Could you group packages automatically by looking at the `SourceRepository`? If multiple packages have the same source repository, chances are high that they are handled as a meta-package I guess.
