### ISSUE TITLE
Merge PackageDistro, PackageDistroTools and gap-infra/integration repositories into one

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#27]
I think this the most efficient all in all:
- the integration tests need the package distro anyway, and ideally the latest version
- we'd ideally like to run them our pull requests adding/modifying/removing packages, that is by far easiest if this is one repo
- all Github Workflows for the `PackageDistro` repo clone the `PackageDistroTools` into `_tools`, so we might as well have them as one?

Any thoughts, concerns, (dis)agreement, ... with this, @ChrisJefferson @james-d-mitchell @ThomasBreuer @wilfwilson ?

UPDATE: PR #130 merged `PackageDistroTools` into this repo.

**Comment by FriedrichRober** [comment]
Or we could add a branch `_tools` and use worktrees as I did for uploading reports to the data branch.

**Comment by FriedrichRober** [comment]
@fingolfin, I tried to cherry-pick the `PackageDistroTools` into `PackageDistro`, but the merge-commits in `PackageDistroTools` cause me trouble. Do you know of a different approach to "merge" repos while preserving somewhat the history?

**Comment by fingolfin** [comment]
We've discussed this on gather and I think @FriedrichRober now used https://github.com/newren/git-filter-repo

**Comment by fingolfin** [comment]
UPDATE: PR #130 merged `PackageDistroTools` into this repo.

**Comment by fingolfin** [comment]
We may or may  it merge the integration repo with this one, bit I see no value in leaving this issue open.
