### ISSUE TITLE
Reports: include direct links to each package job?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#280]
Right now, the reports generated by @FriedrichRober's nice scripts include a single link to the "top" of a workflow run, e.g. https://github.com/gap-system/PackageDistro/actions/runs/2083385173 

Perhaps we could also record for each package a link directly to its job. So e.g. for the `master / digraphs` job, record the link https://github.com/gap-system/PackageDistro/runs/5802230918?check_suite_focus=true -- I am pretty sure the URL resp. all data necessary to reproduce it is/are available inside the job, so in theory it should be just a matter of stuffing it into the JSON data somewhere.

Then, we could use this to turn each package name into a link to "its" report. That'd be quite convenient.

**Comment by FriedrichRober** [comment]
I can try to do this.

**Comment by FriedrichRober** [comment]
Ok, this seems to be a little bit more complicated than expected, but I think [here](https://stackoverflow.com/questions/71240338/obtain-job-id-from-a-workflow-run-using-contexts) is a solution for this. Basically, we need to use Github's REST API, something like `JOBS=$(curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/FriedrichRober/PackageDistro/actions/runs/2083994374/jobs" | jq -r '.jobs');` and then search for its name via `github.job.id`

**Comment by fingolfin** [comment]
Oh wow. I would have expected this to be exposed via one of the "context" objects. But I verified in PR #288 that this really not the case. Weird!

I think we could use this action to make the REST query in a comfortable way: https://github.com/octokit/request-action
