### ISSUE TITLE
PR reports should also cover 4.11.1

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#282]
Right now I've only set it so that the reports for `master` are posted as comment on the PRs. But we should also do this with the 4.11 comments. Only question is: should this go into a separate comment? or all in one big comment? In either case, I think it'd be useful to change the headline from `# Package Evaluation Report` to say `# Package Evaluation Report for master`. But I am not sure how to do that (@FriedrichRober ?)

**Comment by FriedrichRober** [comment]
Yes, I can do that.
