### ISSUE TITLE
Deal with `NormalizInterface`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#285]
So far we build `NormalizInterface` with the `libnormaliz` provided by Ubuntu to us. Unfortunately that made its tests fail, because they are (again: unfortunately) tied very closely to the precise Normaliz version used to build `NormalizInterface`.

To solve that, I've recently switched `NormalizInterface` to build and use the "bundled" version of Normaliz version. That makes its tests pass! ... But unfortunately it makes packages that depend on it fail (HeLP, NConvex), because they now crash:
- In this [log for nconvex](https://github.com/gap-system/PackageDistro/runs/5803107613?check_suite_focus=true) there is the message `free(): invalid pointer` right before a core dump.
- In this [log for help](https://github.com/gap-system/PackageDistro/runs/5803107191?check_suite_focus=true) there is the message 

      gap: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Anyway, somehow this should be resolved. Several options:
1. revert to building against Ubuntu `libnormaliz`: that would be quite convenient, but it requires NormalizInterface to change its tests (perhaps I could bundle multiple tests with it, one for each "supported" Normaliz version). However, note that in some cases, certain NormalzInterface function really behave quite different with different Normaliz versions, so I am not sure how far this could/should be stretched...
2. figure out what causes those crashes with the self-built Normaliz (I don't think it uses `-march=native`).
3. ... any other ideas???

Perhaps @ChrisJefferson has an idea?

**Comment by ChrisJefferson** [comment]
Just to say, I tried hard to poke this, and couldn't reproduce it on my own machine, no matter which testing system I threw at it.

This doesn't seem to be consistently happening? *sigh*, which makes it harder to then track down.

**Comment by fingolfin** [comment]
I am guessing that it might be once again a difference between the machines were it is built vs. the machines it is being run on. But it is definitely not `-march=native`. Maybe some subtle incompatibility in the C++ compiler / C++ std lib? Shouldn't be the case, of course, but ... *shrug*

**Comment by ChrisJefferson** [comment]
Having a quick look at the normaliz page, they seem to say they released 3.9.2 because 3.9.1 was crashing due to openmp issues -- while only reported on mac and windows, it could just be an issue with normaliz?

**Comment by fingolfin** [comment]
We don't compile it with OpenMP support, though.

**Comment by fingolfin** [comment]
I hope that with NormalizInterface 1.3.3 things are better, we'll see once PR #409  is merged, then I can make a PR restoring b47eb5453dfbb190cb905c123a99a72352009f04 ...
