### ISSUE TITLE
Add CI test for `tools/generate_report.py`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#311]
I broke `tools/generate_report.py` in PR #308 due to a trivial copy & paste mistake (since fixed in 30c19b44df5c5a7be5ef6c25ffd68ca11896218d). This reemphasize to me that we should have a CI test for it.

This shouldn't be too hard: we basically need a mock `data` directory with two reports (with their two JSON files and one `report.md`  each). Then the test basically would be to run `tools/generate_report.py` on these two reports, and verify that this does not result in a diff. Then any refactoring which breaks this will be immediately be flagged. Of course those mock reports ideally would test all features, i.e. new/removed/updated packages; and still failing, still passing, newly failing, newly passing.

Of course sometimes we *do* want to change the output. That's fine, though, because then you just run that test locally, and simply add the changes to your commit. This actually is helpful to verify that the change is as intended, and also reviewers of PRs with such changes benefit from it.

The above maybe does not check *all* aspects of the tools, but arguably it covers the most important one.

@FriedrichRober might be willing to help with this. But this is something anyone could in principle pull off, you just need to fiddle a bit with GH Actions, git etc. (so perhaps @wucas also is willing to help out :-) ).

**Comment by FriedrichRober** [comment]
I will work on this.
