### ISSUE TITLE
apt-get install needs an apt-get update first for curlInterface

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/PackageDistro#352]
I noticed curlInterface was failing. The reason is the `apt-get install` was failing because the package it's trying to install isn't distributed any more.

Basically, I think every `apt-get install` needs an `apt-get update` before it (or, doing a single apt-get update at the start of installing).

I wasn't sure the best way of handling this, so didn't make a PR.

**Comment by fingolfin** [comment]
But I already inserted one 5 hours ago in https://github.com/gap-system/PackageDistro/commit/f11865c71e20a0dd84d05014e8bae5e89b1b0170 ?!?

**Comment by ChrisJefferson** [comment]
Sorry, I was looking at failures from more than 5 hours ago, and not noticed the problem was already fixed :)

**Comment by fingolfin** [comment]
Nah, there still is something wrong, but it's not the `apt-get update`, which is there now... see https://github.com/gap-system/PackageDistro/runs/6264505455?check_suite_focus=true

I actually suspect that GitHub screwed something up?

**Comment by fingolfin** [comment]
Argh, no, I just overlooked one case.. hopefully fixed in 6cc3e20ea896a12e941f17aaf05ab73dce465dca.
