### ISSUE TITLE
PackageManager tests are failing, investigate

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#974]
The PackageManager tests run as part of the PackageDistro are currently failing, see [this log](https://github.com/gap-system/PackageDistro/actions/runs/10526345494/job/29167472396).

@mtorpey any ideas what might cause this?

**Comment by fingolfin** [comment]
Seems to have resolved itself, weird, but good

**Comment by fingolfin** [comment]
Unfortunately it does fail again now, see e.g. https://github.com/gap-system/PackageDistro/actions/runs/10630015783/job/29468871632

**Comment by mtorpey** [comment]
This should be fixed in master.  I'll make a release today!

**Comment by mtorpey** [comment]
Keep an eye on #1018 for the new version!

**Comment by fingolfin** [comment]
Thanks it's fixed now :-)
