### ISSUE TITLE
idrel tests are failing in PackageDistribution, investigate

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageDistro#975]
The idrel tests for the current latest stable release of that package are currently failing when run against the latest GAP master. See e.g. [this log](https://github.com/gap-system/PackageDistro/actions/runs/10526345494/job/29167460070).

In particular we see this:
```
########> Diff in /home/runner/gap/pkg/idrel-2.47/tst/idrels.tst:336
# Input is:
mq0 := MonoidPresentationFpGroup( q0 );;
# Expected output:
# But found:
#I  Coset table calculation failed -- trying with bigger table limit
#I  Coset table calculation failed -- trying with bigger table limit
#I  Coset table calculation failed -- trying with bigger table limit
#I  Coset table calculation failed -- trying with bigger table limit
#I  Coset table calculation failed -- trying with bigger table limit
Error, reached the pre-set memory limit
(change it with the -o command line option)
########
```

This makes me suspect that one of the recent changes related to fp groups and coset enumeration likely and unfortunately triggered this regression.

Paging @hulpke @james-d-mitchell @cdwensley to make sure you are aware of this, and just in case you have a quick idea what might cause this. I'll try to look into it myself eventually but don't have time right now as I am busy with GAP Days.

**Comment by hulpke** [comment]
The error gets triggered by `GroupHomomorphismByImages` mapping to an infinite fp group. To test the homomorphism property, GAP attempts to compute a faithful permutation representation.
replacing the call with a `NC` version will avoid the issue.

**Comment by cdwensley** [comment]
Thanks for the hint - will look into it today.

**Comment by cdwensley** [comment]
IdRel v2.48 just released.

**Comment by fingolfin** [comment]
Fixed, thank you!
